require 'fileutils'
DEPLOY_DIR = File.join(File.expand_path('~'), "html")
BUILD_DIR = File.join(File.dirname(__FILE__), "build")

desc "Build the website from source"
task :build do
  puts "## Building website"
  status = system("middleman build")
  puts status ? "OK" : "FAILED"
end

desc "Run the preview server at http://localhost:4567"
task :preview do
  system("middleman server")
end

desc "Deploy website"
task :deploy do
  Dir.mkdir(DEPLOY_DIR) unless File.directory?(DEPLOY_DIR) 
  FileUtils.copy_entry(BUILD_DIR, DEPLOY_DIR) 
end

desc "Build and deploy website"
task :gen_deploy => [:build, :deploy] do
end
